Repository lucas0headshot/GS-SENAC_frontend, pull requests merged in 2024-07, with the labels that each got.

#2 feat: header & routes
  package-lock.json
  package.json
  src/App.jsx
  src/components/gestao-cursos/materia/Materia.jsx
  src/components/gestao-cursos/turma/Turma.jsx
  src/components/header/Header.jsx
  src/components/partials/footer/Footer.jsx
  src/components/partials/footer/footer.module.css
  src/components/partials/header/Header.jsx
  src/components/partials/header/header.module.css
  src/pages/gestao-cursos/home/HomeGestaoCursos.jsx
  src/pages/gestao-cursos/materias/Materias.jsx
  src/pages/gestao-cursos/turmas/Turma.jsx
  src/pages/gestao-cursos/turmas/Turmas.jsx
  src/services/restClient.js
Labels: enhancement

#3 raw: pull_request_template
  .github/pull_request_template.md
Labels: documentation

#4 fix: Routes
  src/App.jsx
Labels: bug

#5 fix: header
  src/App.jsx
  src/components/partials/header/Header.jsx
Labels: bug

#8 docs: README & Templates
  .github/ISSUE_TEMPLATE/reportar-bug.md
  .github/ISSUE_TEMPLATE/sugerir-funcionalidade.md
  .github/logo.png
  LICENSE.txt
  README.md
Labels: documentation

#9 feat: ErrorBoundary
  src/components/ErrorBoundary.jsx
  src/components/Layout.jsx
Labels: enhancement

#10 fix: ErrorBoundary
  src/components/ErrorBoundary.jsx
Labels: bug

#11 feat: SelectFuncionario
  src/components/gestao-cursos/curso/SelectFuncionario.jsx
Labels: enhancement

#13 feat: API_PATH
  API_PATH.js
Labels: enhancement

#15 feat: formatDate Helper
  src/components/helpers/data/formatDate.js
Labels: enhancement

#14 feat: favicon
  index.html
  public/images/banner.png
  public/images/favicon.ico
  public/vite.svg
  src/App.jsx
  src/components/partials/footer/Footer.jsx
  src/index.css
  src/pages/gestao-cursos/home/HomeGestaoCursos.jsx
Labels: enhancement

#16 fix: ajustando API_PATH
  src/components/gestao-cursos/curso/SelectCurso.jsx
  src/components/gestao-cursos/curso/SelectFuncionario.jsx
  src/pages/gestao-cursos/inscricoes/Inscricoes.jsx
Labels: bug

#17 feat: form label e curso na listagem de inscricoes
  src/pages/gestao-cursos/inscricoes/Inscricao.jsx
  src/pages/gestao-cursos/inscricoes/Inscricoes.jsx
Labels: enhancement

#18 feat: cursos
  src/App.jsx
  src/components/gestao-cursos/curso/SelectFuncionario.jsx
  src/pages/gestao-cursos/cursos/Curso.jsx
  src/pages/gestao-cursos/cursos/Cursos.jsx
  src/services/restClient.js
Labels: enhancement

#19 Aula materia
  src/App.jsx
  src/components/gestao-cursos/aula/SelectAula.jsx
  src/components/gestao-cursos/frequencia/Frequencia.jsx
  src/components/gestao-cursos/inscricao/SelectAluno.jsx
  src/components/gestao-cursos/materia/SelectMateria.jsx
  src/components/partials/header/Header.jsx
  src/pages/gestao-cursos/aulas/Aula.jsx
  src/pages/gestao-cursos/aulas/Aulas.jsx
  src/pages/gestao-cursos/frequencia/Frequencia.jsx
  src/pages/gestao-cursos/frequencia/Frequencias.jsx
Labels: enhancement

#21 refactor: cursos
  src/components/helpers/data/formatDate.js
  src/pages/gestao-cursos/cursos/Curso.jsx
  src/pages/gestao-cursos/cursos/Cursos.jsx
Labels: bug

#22 refactor: padronizar
  src/App.jsx
  src/components/helpers/data/getDayFromDate.js
  src/pages/gestao-cursos/aulas/Aula.jsx
  src/pages/gestao-cursos/aulas/Aulas.jsx
  src/pages/gestao-cursos/inscricoes/Inscricao.jsx
  src/pages/gestao-cursos/inscricoes/Inscricoes.jsx
Labels: enhancement

#23 feat: delete cursos button
  src/pages/gestao-cursos/cursos/Cursos.jsx
Labels: enhancement

#24 fix: apresentação
  src/pages/gestao-cursos/cursos/Cursos.jsx
  src/pages/gestao-cursos/materias/Materia.jsx
Labels: enhancement
